services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    image: microfinance-hr-app
    container_name: microfinance-hr-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - APACHE_DOCUMENT_ROOT=/var/www/public
    networks:
      - microfinance-hr-network

networks:
  microfinance-hr-network:
    driver: bridge
