version: '3'

services:
  # Laravel Application
  app:
    image: bitnami/laravel:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306  # This remains 3306 because inside Docker, the container still uses 3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "composer install && 
              php artisan key:generate --force &&
              php artisan migrate &&
              php artisan serve --host=0.0.0.0"

  # Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"  # Changed to 3309 to avoid conflict with local ports
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
