version: '3'

services:
  # Laravel Application
  app:
    image: bitnami/laravel:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306  # This remains 3306 because inside Docker, the container still uses 3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      bash -c "composer install && 
              php artisan key:generate --force &&
              php artisan migrate &&
              php artisan serve --host=0.0.0.0"
    networks:
      - laravel-network

  # Database
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"  # Changed to 3309 to avoid conflict with local ports
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge
