version: '3' 
 
services: 
  app: 
    image: richarvey/nginx-php-fpm:latest 
    ports: 
      - "8000:80" 
    volumes: 
      - .:/var/www/html 
    environment: 
      - APP_ENV=local 
      - APP_KEY=base64:WGSVpWL9Pp8nOdEeHCedntXpXGkLZMnpVz5qESY2Pyk= 
      - DB_HOST=db 
      - DB_DATABASE=laravel 
      - DB_USERNAME=laravel 
      - DB_PASSWORD=laravel 
      - SKIP_COMPOSER=true 
      - WEBROOT=/var/www/html/public 
    depends_on: 
      - db 
 
  db: 
    image: mysql:5.7 
    ports: 
      - "3309:3306" 
    environment: 
      MYSQL_DATABASE: laravel 
      MYSQL_USER: laravel 
      MYSQL_PASSWORD: laravel 
      MYSQL_ROOT_PASSWORD: root 
    volumes: 
      - db_data:/var/lib/mysql 
 
volumes: 
  db_data: 
